export const pokemonTypes = {
  normal: "fa-circle",
  fire: "fa-fire-flame-curved",
  water: "fa-droplet",
  electric: "fa-bolt",
  grass: "fa-seedling",
  ice: "fa-snowflake",
  fighting: "fa-hand-fist",
  poison: "fa-skull-crossbones",
  ground: "fa-mountain",
  flying: "fa-feather",
  psychic: "fa-eye",
  bug: "fa-bug",
  rock: "fa-gem fa-rotate-180",
  ghost: "fa-",
  dragon: "fa-dragon",
  dark: "fa-moon fa-rotate-by dark-icon",
  steel: "fa-magnet",
  fairy: "fa-star-of-david",
};
